/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package musicbox;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 * TruckTypeChoice --- frame to allow user to choose their type of food truck
 *
 * @author Ashwika Katiyar
 */
public class TruckTypeChoice extends javax.swing.JFrame {

    /**
     * Creates new form truckTypeChoice
     */
    public TruckTypeChoice() {
        initComponents();
        ImageIcon bg = new ImageIcon("Dropdown.png");
        jLabel1.setIcon(bg);
        this.setSize(bg.getIconWidth(), bg.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start = new javax.swing.JButton();
        truckType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start);
        start.setBounds(230, 420, 72, 23);

        truckType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Burgers and Sliders", "Desserts", "Pizza", "Breakfast and Brunch", "Crepes", "Tacos and Burritos" }));
        getContentPane().add(truckType);
        truckType.setBounds(160, 380, 210, 23);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 540, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * startActionPerformed --- opens a new frame for the user to make a new
     * playlist
     *
     * @param evt
     */
    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        String type = (String) truckType.getSelectedItem();
        NewPlayListEdit f3;
        try {
            f3 = new NewPlayListEdit(type);
            f3.setVisible(true);
            this.dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TruckTypeChoice.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_startActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton start;
    private javax.swing.JComboBox<String> truckType;
    // End of variables declaration//GEN-END:variables
}
